name: ESP32 Camera Bridge
slug: esp32_cam_bridge
version: "1.0.3"
description: Stream ESP32-CAM frames to ESP32 TFT

url: https://github.com/21Chard/esp32_cam_bridge

startup: application
boot: auto

host_network: true

init: false

arch:
  - amd64

ports:
  8088/tcp: 8088

options:
  camera_url: "http://192.168.100.13:8080"

schema:
  camera_url: str
